# -*- coding: utf-8 -*-
"""Alzheimer's disease new code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8o0rdOsqKodz6ewdEj0cCR14b9OW3hw
"""

!pip install cartopy
import  tensorflow as tf

from google.colab import drive

('/content/drive/MyDrive')

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import random 
import cv2

import keras
from PIL import Image
from random import randint
from keras.layers import GlobalAveragePooling2D, GlobalMaxPooling2D, Reshape, Dense, multiply, Permute, Concatenate, Conv2D, Add, Activation, Lambda
from keras import backend as K
from keras.activations import sigmoid
from keras import layers
from keras.preprocessing.image import ImageDataGenerator
from keras import initializers
from keras.models import Sequential

!python --version

pip install tensorflow

import keras
from keras.utils import to_categorical

print(tf.__version__)
print(keras.__version__)

train_path= "/content/drive/MyDrive/Alzheimer_s Dataset-2/train"
test_path= "/content/drive/MyDrive/Alzheimer_s Dataset-2/test"

import tensorflow as tf
from tensorflow import keras
import warnings
from tensorflow.keras import layers

# Load the dataset
train_data = keras.preprocessing.image_dataset_from_directory(
    '/content/drive/MyDrive/Alzheimer_s Dataset/train',
    image_size=(150, 150),
    batch_size=32,
    shuffle=True,
    seed=42,
    validation_split=0.2,
    subset='training'
)

test_data = keras.preprocessing.image_dataset_from_directory(
    '/content/drive/MyDrive/Alzheimer_s Dataset/test',
    image_size=(150, 150),
    batch_size=32,
    shuffle=True,
    seed=42,
    validation_split=0.2,
    subset='validation'
)

pip install matplotlib-venn